# this command is part of the "build-and-test" target.
# it runs 'go build' and tells pare to crash on any non-zero exit code.
# if the 'go build' command fails, pare will exit with code 1
[targets.build-and-test.commands.build]
exec = "go build -o pare ."
crash = true

# this command is part of the 'build-and-test' target.
# this command runs 'go test' and tells pare to crash on any non-zero exit code.
# if this command fails, pare will exit with code 1
# [targets.build-and-test.commands.test]
[targets.build-and-test.commands.test]
exec = "go test ./..."
crash = true
