version: 2
jobs:
  build:
    working_directory: /go/src/github.com/arschles/pare
    docker:
      - image: quay.io/deis/go-dev:v1.2.0
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: dep ensure
      - run:
          name: Run build
          command: go build -o pare .
  test:
    working_directory: /go/src/github.com/arschles/pare
    docker:
       - image: quay.io/deis/go-dev:v1.2.0
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: dep ensure
      - run:
          name: Run tests
          command: go test ./...
  linux:
    working_directory: /go/src/github.com/arschles/pare
    docker:
      - image: quay.io/deis/go-dev:v1.2.0
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: dep ensure
      - run:
          name: Build for linux
          command: CGO_ENABLED=0 GOOS=linux GOARCH=amd64 -o cross/pare_linux_amd64 .
  darwin:
    working_directory: /go/src/github.com/arschles/pare
    docker:
      - image: quay.io/deis/go-dev:v1.2.0
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: dep ensure
      - run:
          name: Build
          command: CGO_ENABLED=0 GOOS=darwin GOARCH=amd64 -o cross/pare_darwin_amd64 .
  windows:
    working_directory: /go/src/github.com/arschles/pare
    docker:
      - image: quay.io/deis/go-dev:v1.2.0
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: dep ensure
      - run:
          name: Build for linux
          command: CGO_ENABLED=0 GOOS=windows GOARCH=amd64 -o cross/pare_windows_amd64.exe .
  deploy:
    working_directory: /go/src/github.com/arschles/pare
    docker:
      - image: google/cloud-sdk:slim
    steps:
      - run:
          name: Activate GCS
          command: .gcs_activate.sh
          working_directory: scripts
      - run:
          name: Upload to GCS
          command: .gcs_upload.sh
workflows:
  version: 2
  master:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - test:
          filters:
            branches:
              only: master
      - deploy:
          requires:
            - build
            - test
          filters:
            branches:
              only: master
